export const PROVIDERS = [
  {
    id: "cloudflare",
    name: "Cloudflare",
    steps: [
      "Log in at dash.cloudflare.com and click your domain.",
      "In the left sidebar, click DNS → Records.",
      "Click the blue \"Add record\" button.",
      "Set Type to TXT, then paste the Name and Content values shown below.",
      "Leave TTL on Auto and click Save.",
    ],
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    steps: [
      "Log in at godaddy.com → My Products → next to your domain click DNS.",
      "Under DNS Records, click \"Add New Record\".",
      "Choose Type TXT, then paste the Name and Value shown below.",
      "GoDaddy tip: enter only the part before your domain in Name (e.g. _dmarc, not _dmarc.yourdomain.com).",
      "Click Save. Changes usually apply within an hour.",
    ],
  },
  {
    id: "namecheap",
    name: "Namecheap",
    steps: [
      "Log in → Domain List → Manage next to your domain.",
      "Open the Advanced DNS tab.",
      "Click \"Add New Record\" → choose TXT Record.",
      "In Host, enter only the subdomain part (e.g. _dmarc or @). Paste the Value below.",
      "Click the green check to save.",
    ],
  },
  {
    id: "google",
    name: "Squarespace / Google Domains",
    steps: [
      "Log in to your domain dashboard and open DNS settings for the domain.",
      "Find Custom Records and click \"Add record\".",
      "Set Host to the name shown below, Type to TXT, and paste the Data value.",
      "Save. Propagation is usually minutes.",
    ],
  },
  {
    id: "route53",
    name: "AWS Route 53",
    steps: [
      "Open the Route 53 console → Hosted zones → your domain.",
      "Click \"Create record\".",
      "Record name: the name shown below. Record type: TXT.",
      "In Value, paste the record wrapped in double quotes.",
      "Click \"Create records\".",
    ],
  },
  {
    id: "other",
    name: "Somewhere else",
    steps: [
      "Log in where you bought your domain and find DNS settings, DNS management, or Zone editor.",
      "Add a new record of type TXT.",
      "Use the Name/Host and Value shown below. If a full name is rejected, try just the part before your domain (e.g. _dmarc).",
      "Save. Most providers apply changes within an hour; some take up to 24.",
    ],
  },
];

export function recordsForResult(result) {
  const domain = result.domain;
  const recs = [];
  if (result.dmarc.status === "fail" && !result.dmarc.record) {
    recs.push({
      label: "DMARC record (start monitoring safely)",
      host: `_dmarc.${domain}`,
      type: "TXT",
      value: `v=DMARC1; p=none; rua=mailto:dmarc-reports@${domain}`,
      note: "p=none changes nothing about delivery — it only starts sending you reports. Sign up for a free InboxGuard dashboard and we give you a reporting address that turns those reports into charts and alerts automatically.",
    });
  }
  if (result.spf.status === "fail" && !result.spf.record) {
    recs.push({
      label: "SPF record",
      host: domain,
      type: "TXT",
      value: "v=spf1 include:_spf.google.com ~all",
      note: "This example authorizes Google Workspace. Replace the include with your provider's: Microsoft 365 → include:spf.protection.outlook.com · Zoho → include:zohomail.com. Sending from several services? Chain includes in one record, never create two SPF records.",
    });
  }
  if (result.dkim.status !== "pass") {
    recs.push({
      label: "DKIM — enable it at your email provider (not a copy-paste record)",
      host: null,
      type: null,
      value: null,
      note: "DKIM keys are generated by your email provider. Google Workspace: Admin console → Apps → Google Workspace → Gmail → Authenticate email → Generate new record, then add the TXT record it gives you. Microsoft 365: Defender portal → Email authentication settings → DKIM → enable for your domain. Zoho: Admin console → Domains → your domain → Email configuration → DKIM.",
    });
  }
  return recs;
}
